version: "3"

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - ~/data/wordpress:/var/www/html
    restart: on-failure

  mariadb:
    container_name: mariadb 
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_USER_PASSWORD: $MYSQL_USER_PASSWORD
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    restart: on-failure

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      DOMAIN_NAME: $DOMAIN_NAME
      WP_ADMIN: $WP_ADMIN
      WP_ADMIN_PASSWORD: $WP_ADMIN_PASSWORD
      WP_ADMIN_EMAIL: $WP_ADMIN_EMAIL
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_USER_PASSWORD: $MYSQL_USER_PASSWORD
    ports:
      - 9000
    networks:
      - inception
    volumes:
      - ~/data/wordpress:/var/www/html
    restart: on-failure

networks:
  inception:
